### ISSUE TITLE
社区第一版上线

### ISSUE THREAD

**Issue by awong1900** [zuqiuxunlian/wechat-cnode#1]
- [x] 修改API地址

- [x] 修改描述

- [x] 修改图标LOGO

- [x] 修改TAB栏，最好有全局修改

- [x] 修改分享标题，代码改为全局的最好

- [x] 修改客服消息微信号

- [x] 意见反馈？

- [x] 修改版本号

**Comment by RoachieDev** [comment]
https://github.com/zuqiuxunlian/wechat-cnode/pull/2
