### ISSUE TITLE
发帖和回帖问题

### ISSUE THREAD

**Issue by awong1900** [zuqiuxunlian/wechat-cnode#14]
- [x] @回帖设计有些突兀，本来想看图片放大，结果突然变成回帖. 如果不好设计，可去掉此功能.
- [x] 回帖后丢掉路径。回帖后用户左滑直接退出了程序。
- [x] 【让步接受】回帖的位置，如果回复比较多，下拉后，需要拉回去才能回帖，体验有一些不友好.
- [x] 删除回帖或发帖，用户可能会想删除发错的帖子或回复。如果能修改回帖当然更好。在主贴下面，我要评论旁边增加编辑，删除按钮？

- [x] 隐藏回帖功能。小程序审核时会对UGC内容加强审核，是否可以做一个动态的形式来过审。

- [x] 发帖入口有点深. 用浮动按钮会不会好些？像主页按钮一样。
- [x] 发帖的板块选择可以用其他方式吗？菜单弹出位置不够了。~~现在发新闻板块好像不行~~ 目前这种形式还是有限，扩展性很差，而且已经满额了。

- [x] 每次列表请求或帖子请求，都会自动发login请求？可能是一个bug
![image](https://user-images.githubusercontent.com/4022612/56549923-be241600-65b6-11e9-92cf-78b2cc7ddd45.png)

- [x] 回帖或发帖，标题多余5个字即可。分析目前的社区，包括Facebook小组，基本不要输入标题，直接写内容。

**Comment by awong1900** [comment]
## 动态设置API
`GET /weapp_config`

最好同时隐藏发帖和回帖窗口。

|参数|描述|
|-----|----|
|has_post| 是否开放小程序发帖和回帖|
|card_ads|首页推广，未来使用|
 

`200`
```
{
    "success": true,
    "data": {
        "has_post": false,
        "card_ads": [
            {
                "label": "",
                "herf": "",
                "img_src": ""
            }
        ]
    }
}
```

**Comment by RoachieDev** [comment]
> 删除回帖或发帖，用户可能会想删除发错的帖子或回复。如果能修改回帖当然更好。在主贴下面，我要评论旁边增加编辑，删除按钮？

删除回帖的接口补充写一下。帖子修改的不是很好弄，PC端发布时候内容(文字 + 图片) 用我们现在小程序发帖的界面展示的话，不太好把文字和图片分割出来，暂时先不做。

---

> 发帖的板块选择可以用其他方式吗？菜单弹出位置不够了。现在发新闻板块好像不行 目前这种形式还是有限，扩展性很差，而且已经满额了

1. 现在发帖是可以发新闻版块的。
2. 这块儿改的话，帖子列表切换模块的部分也要改动。目前这种板块选择的方式使用的是和微信风格的选方式(调用的([wx.showActionSheet](https://developers.weixin.qq.com/miniprogram/dev/api/wx.showActionSheet.html)) 暂时只支持6个选项，现阶段差不多是够的。所以这里目前就用这种方式。 

---

> 回帖或发帖，标题多余5个字即可。分析目前的社区，包括Facebook小组，基本不要输入标题，直接写内容。

这部分做改动，你理解一下“博客”和“微博”的区别。你说的Facebook小组还有你给我看的小程序那种不算是博客社区，更像是轻量级的社交（类似微博、动态、说说、空间状态）这种形态的发布内容不需要标题，甚至发个简单的符号都可以。我们目前的更倾向的是一种博客社区，完整的博客必须是标题+内容，一般还会限定内容多于140个字，这才更像博客，内容会显的更加专业。
你所说的那种轻量级的发布的方式，可以在**首页新增一个“足球圈” 的模块**，内容展示的话可以类似微博、Facebook 动态空间一样的形式。
