### ISSUE TITLE
优雅的设计

### ISSUE THREAD

**Issue by awong1900** [zuqiuxunlian/wechat-cnode#15]
- [x] 帖子用户名显示改成昵称？因为用户名都是机器取得.意义不是很大.
- [x] 分享/ 转发 按钮是否做一个到帖子页面上？这样可以明显提高转发率？
- [x] 小程序分享的主图更换。

**Comment by RoachieDev** [comment]
> 1. 帖子用户名显示改成昵称

https://bbt.zuqiuxunlian.com/api/v1/topic/5cbe73b99f670f4df70762c7?mdrender=false 这个接口里面的 author 数据都添加一个 nickName字段吧

> 2. 分享/ 转发 按钮是否做一个到帖子页面上

已添加， 效果大概是这样:
![image](https://user-images.githubusercontent.com/17998436/56588453-f575df80-6615-11e9-947a-00f1ff0b021f.png)


> 3. 小程序分享的主图更换。

你那边儿让设计出一个图片(图片长宽比为 5:4 )传到七牛云，给我图片链接地址我设置一下就行。

**Comment by awong1900** [comment]
3. https://static.zuqiuxunlian.com/2002_5_4.jpg
