### ISSUE TITLE
发帖时经常内容填完，发现需要登录，导致内容丢失。

### ISSUE THREAD

**Issue by awong1900** [zuqiuxunlian/wechat-cnode#34]
这个特别影响首次回帖的心情。

**Comment by RoachieDev** [comment]
已修改： https://github.com/zuqiuxunlian/wechat-cnode/pull/35

**Comment by awong1900** [comment]
点击快捷发帖按钮弹出了授权上拉框。 能不能评论和回复可以改成同样的模式？
