### ISSUE TITLE
开启审核隐藏模式，悬浮发帖按钮没有被隐藏。

### ISSUE THREAD

**Issue by awong1900** [zuqiuxunlian/wechat-cnode#38]
![14241562251437_ pic](https://user-images.githubusercontent.com/4022612/60674973-e7fa9280-9ead-11e9-9b22-f06248556858.jpg)
![Uploading 14251562251449_.pic.jpg…]()

**Comment by RoachieDev** [comment]
已修复： https://github.com/zuqiuxunlian/wechat-cnode/commit/7ad978e44f0556f18c96bec7f837bb76b36a7db9#commitcomment-34204546
