### ISSUE TITLE
java代码提示libpng警告：iCCP：已知不正确的sRGB配置文件，怎么修改都去不掉

### ISSUE THREAD

**Issue by llccde** [zuqiuxunlian/wechat-cnode#47]
[signOn.zip](https://github.com/zuqiuxunlian/wechat-zuqiujiaolian/files/14787681/signOn.zip)
我的java作业出现一个奇怪的bug，代码运行总是提示libpng warning: iCCP: known incorrect sRGB profile，我修改了所有与ImageIO
相关的代码，但这个提示就像闹鬼了一样，一直存在。我使用的windows10和vscode，不确定在别的编译器上有没有问题。我怀疑他是在window.java或者itemPageFrame.java中产生的，但就是无法去除

**Comment by awong1900** [comment]
off topic.
